# GitHub Pages Configuration for CERRF.org

# Site settings
name: "CERRF - Cyber Education, Research & Resilience Foundation"
description: "Empowering the next generation through cybersecurity education, research, and resilience-building initiatives."
url: "https://cerrf.org"
baseurl: ""

# Theme settings
theme: jekyll-theme-cayman # Change as needed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social media links
social:
  github: cerrf-org
  linkedin: company/cerrf
  instagram: cerrf.social

# Google Analytics (Replace with actual tracking ID)
google_analytics: UA-XXXXXXXXX-X

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from Jekyll build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - _site/
